/* Bundled dictionary powering the "Dictionary" knowledge card in search.
   Searching a single word shows its part of speech and definition — offline,
   so it works with no network. ~130 common words. Extend freely. */
(function () {
  "use strict";
  window.DICTIONARY = {
    abate: { pos: "verb", def: "To become less intense or widespread; to reduce in amount or degree." },
    aberration: { pos: "noun", def: "A departure from what is normal, usual, or expected." },
    abundant: { pos: "adjective", def: "Existing or available in large quantities; plentiful." },
    accolade: { pos: "noun", def: "An award or expression of praise." },
    acumen: { pos: "noun", def: "The ability to make good judgments and quick decisions." },
    adept: { pos: "adjective", def: "Very skilled or proficient at something." },
    adversity: { pos: "noun", def: "Difficulties; a difficult or unpleasant situation." },
    aesthetic: { pos: "adjective", def: "Concerned with beauty or the appreciation of beauty." },
    alleviate: { pos: "verb", def: "To make suffering or a problem less severe." },
    ambiguous: { pos: "adjective", def: "Open to more than one interpretation; not having one obvious meaning." },
    ambivalent: { pos: "adjective", def: "Having mixed or contradictory feelings about something." },
    amiable: { pos: "adjective", def: "Having a friendly and pleasant manner." },
    anomaly: { pos: "noun", def: "Something that deviates from what is standard or expected." },
    arduous: { pos: "adjective", def: "Involving or requiring strenuous effort; difficult and tiring." },
    articulate: { pos: "adjective", def: "Able to express ideas fluently and clearly." },
    astute: { pos: "adjective", def: "Having or showing sharp judgment; shrewd." },
    augment: { pos: "verb", def: "To make something greater by adding to it." },
    austere: { pos: "adjective", def: "Severe or strict in manner; plain and without comfort." },
    benevolent: { pos: "adjective", def: "Well meaning and kindly." },
    benign: { pos: "adjective", def: "Gentle and kindly; (of a condition) not harmful." },
    brevity: { pos: "noun", def: "Concise and exact use of words; shortness of time." },
    buoyant: { pos: "adjective", def: "Able to float; cheerful and optimistic." },
    candor: { pos: "noun", def: "The quality of being open and honest; frankness." },
    capricious: { pos: "adjective", def: "Given to sudden changes of mood or behavior." },
    catalyst: { pos: "noun", def: "A person or thing that causes an event; a substance that speeds a reaction." },
    caustic: { pos: "adjective", def: "Sarcastic in a bitter way; able to burn or corrode." },
    circumvent: { pos: "verb", def: "To find a way around an obstacle or rule." },
    coalesce: { pos: "verb", def: "To come together to form one group or mass." },
    cogent: { pos: "adjective", def: "Clear, logical, and convincing." },
    commend: { pos: "verb", def: "To praise formally or officially." },
    compelling: { pos: "adjective", def: "Evoking strong interest or attention; convincing." },
    concise: { pos: "adjective", def: "Giving a lot of information clearly and in few words." },
    conundrum: { pos: "noun", def: "A confusing and difficult problem or question." },
    copious: { pos: "adjective", def: "Abundant in supply or quantity." },
    cordial: { pos: "adjective", def: "Warm and friendly." },
    corroborate: { pos: "verb", def: "To confirm or give support to a statement or finding." },
    craven: { pos: "adjective", def: "Contemptibly lacking in courage; cowardly." },
    cryptic: { pos: "adjective", def: "Having a meaning that is mysterious or obscure." },
    deference: { pos: "noun", def: "Humble submission and respect to another's wishes." },
    deft: { pos: "adjective", def: "Neatly skillful and quick in movement." },
    deride: { pos: "verb", def: "To express contempt for; to ridicule." },
    diligent: { pos: "adjective", def: "Showing careful and persistent effort in work." },
    diminish: { pos: "verb", def: "To make or become less." },
    discern: { pos: "verb", def: "To perceive or recognize something clearly." },
    disparate: { pos: "adjective", def: "Essentially different in kind; not able to be compared." },
    dubious: { pos: "adjective", def: "Hesitating or doubting; not to be relied upon." },
    eloquent: { pos: "adjective", def: "Fluent or persuasive in speaking or writing." },
    elusive: { pos: "adjective", def: "Difficult to find, catch, or achieve." },
    eminent: { pos: "adjective", def: "Famous and respected within a field." },
    empathy: { pos: "noun", def: "The ability to understand and share the feelings of another." },
    endeavor: { pos: "noun", def: "An attempt to achieve a goal; earnest effort." },
    ephemeral: { pos: "adjective", def: "Lasting for a very short time." },
    epitome: { pos: "noun", def: "A perfect example of a quality or type." },
    equanimity: { pos: "noun", def: "Calmness and composure, especially in a difficult situation." },
    erudite: { pos: "adjective", def: "Having or showing great knowledge or learning." },
    exacerbate: { pos: "verb", def: "To make a problem or bad situation worse." },
    exemplary: { pos: "adjective", def: "Serving as a desirable model; very good." },
    fastidious: { pos: "adjective", def: "Very attentive to accuracy and detail." },
    feasible: { pos: "adjective", def: "Possible to do easily or conveniently." },
    fervent: { pos: "adjective", def: "Having or displaying passionate intensity." },
    fleeting: { pos: "adjective", def: "Lasting for a very short time." },
    fortuitous: { pos: "adjective", def: "Happening by chance, often a lucky one." },
    frivolous: { pos: "adjective", def: "Not having any serious purpose or value." },
    frugal: { pos: "adjective", def: "Sparing or economical with money or food." },
    garrulous: { pos: "adjective", def: "Excessively talkative, especially about trivial matters." },
    gregarious: { pos: "adjective", def: "Fond of company; sociable." },
    hapless: { pos: "adjective", def: "Unlucky; unfortunate." },
    harbinger: { pos: "noun", def: "A person or thing that signals the approach of another." },
    hinder: { pos: "verb", def: "To create difficulties that delay or obstruct." },
    hubris: { pos: "noun", def: "Excessive pride or self-confidence." },
    idyllic: { pos: "adjective", def: "Extremely happy, peaceful, or picturesque." },
    immutable: { pos: "adjective", def: "Unchanging over time; unable to be changed." },
    impartial: { pos: "adjective", def: "Treating all rivals or disputants equally; fair." },
    impede: { pos: "verb", def: "To delay or prevent by obstructing." },
    incisive: { pos: "adjective", def: "Intelligently analytical and clear-thinking." },
    indelible: { pos: "adjective", def: "Making marks that cannot be removed; unforgettable." },
    ineffable: { pos: "adjective", def: "Too great or extreme to be expressed in words." },
    innate: { pos: "adjective", def: "Inborn; natural rather than learned." },
    innocuous: { pos: "adjective", def: "Not harmful or offensive." },
    insatiable: { pos: "adjective", def: "Impossible to satisfy." },
    intrepid: { pos: "adjective", def: "Fearless; adventurous." },
    intricate: { pos: "adjective", def: "Very complicated or detailed." },
    jubilant: { pos: "adjective", def: "Feeling or expressing great happiness and triumph." },
    juxtapose: { pos: "verb", def: "To place close together for contrasting effect." },
    keen: { pos: "adjective", def: "Eager; sharp or highly developed." },
    laconic: { pos: "adjective", def: "Using very few words." },
    lament: { pos: "verb", def: "To express sorrow, regret, or disappointment." },
    languid: { pos: "adjective", def: "Displaying a pleasant lack of energy; relaxed and slow." },
    lavish: { pos: "adjective", def: "Sumptuously rich, elaborate, or luxurious." },
    lethargic: { pos: "adjective", def: "Sluggish and apathetic; lacking energy." },
    lucid: { pos: "adjective", def: "Expressed clearly; easy to understand." },
    magnanimous: { pos: "adjective", def: "Generous or forgiving, especially toward a rival." },
    malleable: { pos: "adjective", def: "Able to be shaped; easily influenced." },
    meticulous: { pos: "adjective", def: "Showing great attention to detail; very careful." },
    mitigate: { pos: "verb", def: "To make less severe, serious, or painful." },
    mundane: { pos: "adjective", def: "Lacking interest or excitement; ordinary." },
    nascent: { pos: "adjective", def: "Just coming into existence and beginning to develop." },
    nebulous: { pos: "adjective", def: "In the form of a cloud; vague or ill-defined." },
    nefarious: { pos: "adjective", def: "Wicked or criminal." },
    nonchalant: { pos: "adjective", def: "Feeling or appearing casually calm and relaxed." },
    nostalgia: { pos: "noun", def: "A sentimental longing for the past." },
    obsolete: { pos: "adjective", def: "No longer produced or used; out of date." },
    obstinate: { pos: "adjective", def: "Stubbornly refusing to change one's opinion or course." },
    opaque: { pos: "adjective", def: "Not able to be seen through; hard to understand." },
    opulent: { pos: "adjective", def: "Ostentatiously rich and luxurious." },
    ornate: { pos: "adjective", def: "Elaborately or heavily decorated." },
    paramount: { pos: "adjective", def: "More important than anything else; supreme." },
    pensive: { pos: "adjective", def: "Engaged in deep or serious thought." },
    perceptive: { pos: "adjective", def: "Having or showing sensitive insight." },
    perennial: { pos: "adjective", def: "Lasting or existing for a long or seemingly infinite time." },
    placid: { pos: "adjective", def: "Calm and peaceful, with little movement or activity." },
    plausible: { pos: "adjective", def: "Seeming reasonable or probable." },
    pragmatic: { pos: "adjective", def: "Dealing with things sensibly and realistically." },
    precarious: { pos: "adjective", def: "Not securely held; dangerously likely to fall or fail." },
    prevalent: { pos: "adjective", def: "Widespread in a particular area or at a particular time." },
    profound: { pos: "adjective", def: "Very great or intense; showing deep insight." },
    prolific: { pos: "adjective", def: "Producing much fruit, offspring, or work." },
    prudent: { pos: "adjective", def: "Acting with or showing care and thought for the future." },
    quaint: { pos: "adjective", def: "Attractively unusual or old-fashioned." },
    quell: { pos: "verb", def: "To put an end to, typically by force; to suppress." },
    rancor: { pos: "noun", def: "Bitterness or resentfulness, especially long-standing." },
    reclusive: { pos: "adjective", def: "Avoiding the company of other people; solitary." },
    rectify: { pos: "verb", def: "To put right; to correct." },
    redundant: { pos: "adjective", def: "No longer needed; superfluous." },
    relentless: { pos: "adjective", def: "Unceasingly intense; harsh or inflexible." },
    resilient: { pos: "adjective", def: "Able to recover quickly from difficulties; tough." },
    reticent: { pos: "adjective", def: "Not revealing one's thoughts readily; reserved." },
    reverent: { pos: "adjective", def: "Feeling or showing deep respect." },
    sagacious: { pos: "adjective", def: "Having keen mental discernment and good judgment." },
    scrutinize: { pos: "verb", def: "To examine or inspect closely and thoroughly." },
    serene: { pos: "adjective", def: "Calm, peaceful, and untroubled." },
    spurious: { pos: "adjective", def: "Not genuine, authentic, or true." },
    stoic: { pos: "adjective", def: "Enduring hardship without showing feelings or complaint." },
    substantiate: { pos: "verb", def: "To provide evidence to support or prove the truth of." },
    superfluous: { pos: "adjective", def: "Unnecessary, especially through being more than enough." },
    tangible: { pos: "adjective", def: "Perceptible by touch; clear and definite; real." },
    tenacious: { pos: "adjective", def: "Tending to keep a firm hold; persistent." },
    tentative: { pos: "adjective", def: "Not certain or fixed; done without confidence." },
    transient: { pos: "adjective", def: "Lasting only for a short time; impermanent." },
    trivial: { pos: "adjective", def: "Of little value or importance." },
    ubiquitous: { pos: "adjective", def: "Present, appearing, or found everywhere." },
    unprecedented: { pos: "adjective", def: "Never done or known before." },
    vehement: { pos: "adjective", def: "Showing strong feeling; forceful and intense." },
    venerate: { pos: "verb", def: "To regard with great respect; to revere." },
    verbose: { pos: "adjective", def: "Using or expressed in more words than are needed." },
    vindicate: { pos: "verb", def: "To clear of blame or suspicion; to justify." },
    viable: { pos: "adjective", def: "Capable of working successfully; feasible." },
    vigilant: { pos: "adjective", def: "Keeping careful watch for possible danger or difficulties." },
    vivid: { pos: "adjective", def: "Producing powerful, clear images in the mind; intensely bright." },
    voracious: { pos: "adjective", def: "Wanting or devouring great quantities; very eager." },
    whimsical: { pos: "adjective", def: "Playfully quaint or fanciful; unpredictable." },
    zealous: { pos: "adjective", def: "Having or showing great energy or enthusiasm for a cause." },
    zenith: { pos: "noun", def: "The time at which something is most powerful; the peak." },
  };
})();
